module.exports = {
  ALL: null,
  GAS: 1,
  DIESEL: 2,
  GAS_AND_DIESEL: 3,
  HYBRID: 4,
  GAS_AND_HYBRID: 5,
  DIESEL_AND_HYBRID: 6,
  OTHER: 8,
  GAS_AND_OTHER: 9,
  DIESEL_AND_OTHER: 10,
  GAS_AND_DIESEL_AND_OTHER: 11,
  HYBRID_AND_OTHER: 12,
  GAS_AND_HYBRID_AND_OTHER: 13,
  DIESEL_AND_HYBRID_AND_OTHER: 14,
  GAS_AND_DIESEL_AND_HYBRID_AND_OTHER: 15
};
